name: EC2 deploy from docker

on:
  push:
    branches: ["QA"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_REGISTRY: ghcr.io
  APP_NAME: nodewebapp
  APP_PORT: 5454

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug - List Repository Structure
        run: |
          echo "Listing repository structure:"
          ls -R

      - name: Build and Push Docker Image
        working-directory: ./L2-NodeJsWebApp
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.TAG }} .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.TAG }}
          echo "Docker image built and pushed successfully."





