name: EC2 deploy from docker

on:
  push:
    branches: ["QA"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_REGISTRY: ghcr.io
  APP_NAME: nodewebapp
  APP_PORT: 5454

jobs:
  deploy-qa:
    uses: ./.github/workflows/build_and_deploy_with_setup.yml
    with:
      env: qa
      tag: latest
      ec2_hosts: ${{ secrets.EC2_HOSTS_QA }}
      ec2_key: ${{ secrets.EC2_KEY_QA }}

  deploy-main:
    uses: ./.github/workflows/build_and_deploy_with_setup.yml
    with:
      env: production
      tag: latest
      ec2_hosts: ${{ secrets.EC2_HOSTS_PRD }}
      ec2_key: ${{ secrets.EC2_KEY_PRD }}
